name: Release container images

on:
  push:
    branches: [master]

env:
  ApplicationName: mcrouter
  QuayImageName: liupeng0518/mcrouter
  AppVersion: "v2024.07.29.00"
  DOCKERFILE_PATH: './mcrouter/scripts/docker/almalinux/Dockerfile'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to docker.io
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Build and push multi-arch latest image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.QuayImageName }}:${{ env.AppVersion }}, ${{ env.QuayImageName }}:latest
